[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.0 MB/s eta 0:00:00


In [2]:
import torch

In [29]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
  max_x = x.max(dim=dim, keepdim=True).values
  e_x = torch.exp(x-max_x)
  return e_x/e_x.sum(dim=dim, keepdim=True)

In [30]:
# 🧪 Debug
x = torch.tensor([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

tensor([[3.],
        [3.]])
Output: tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
tensor([[3.],
        [3.]])
Sum:    tensor(2.0000)
Ref:    tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [31]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
tensor([3.])
  ✅ [1/3] Basic 1-D (3.0ms)
tensor([[0.8638],
        [1.7320],
        [1.7828],
        [0.5970]])
  ✅ [2/3] 2-D along dim=-1 (2.2ms)
tensor([1002.])
  ✅ [3/3] Numerical stability (1.3ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (6.6ms total)
  Progress saved. Run status() to see your dashboard.

