[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/04_layernorm.ipynb)

# 🟡 Medium: Implement LayerNorm

Implement **Layer Normalization** from scratch.

$$\text{LayerNorm}(x) = \gamma \cdot \frac{x - \mu}{\sqrt{\sigma^2 + \epsilon}} + \beta$$

where $\mu$ and $\sigma^2$ are computed over the **last dimension**.

### Signature
```python
def my_layer_norm(
    x: torch.Tensor,      # input
    gamma: torch.Tensor,   # scale (same size as last dim)
    beta: torch.Tensor,    # shift (same size as last dim)
    eps: float = 1e-5
) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `F.layer_norm` or `torch.nn.LayerNorm`
- Normalize over the last dimension only
- Must support autograd

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.4 MB/s eta 0:00:00


In [4]:
import torch
import math

In [15]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_layer_norm(x, gamma, beta, eps=1e-5):
    x_mean = x.mean(dim = -1, keepdim = True)
    x_var = x.var(dim = -1, keepdim = True, unbiased=False)
    return gamma*(x-x_mean)/torch.sqrt(x_var+eps)+beta

In [13]:
# 🧪 Debug
x = torch.randn(2, 8)
gamma = torch.ones(8)
beta = torch.zeros(8)

out = my_layer_norm(x, gamma, beta)
ref = torch.nn.functional.layer_norm(x, [8], gamma, beta)

print("Your output mean:", out.mean(dim=-1))   # should be ~0
print("Your output std: ", out.std(dim=-1))     # should be ~1
print("Match ref?      ", torch.allclose(out, ref, atol=1e-4))

tensor([[0.1985],
        [0.3507]])
tensor([[0.5980],
        [0.3688]])
Your output mean: tensor([-2.2352e-08, -2.9802e-08])
Your output std:  tensor([1.0690, 1.0690])
Match ref?       True


In [14]:
# ✅ SUBMIT
from torch_judge import check
check("layernorm")


🧪 Testing: Implement LayerNorm (Medium)
──────────────────────────────────────────────────
tensor([[[ 0.1302],
         [ 0.0485],
         [ 0.0383]],

        [[ 0.1185],
         [-0.5057],
         [ 0.1380]]])
tensor([[[1.2943],
         [0.5691],
         [1.8342]],

        [[1.4456],
         [0.9413],
         [0.8666]]])
  ✅ [1/3] Shape and basic behavior (2.0ms)
tensor([[ 0.0058],
        [ 0.1493],
        [ 0.0709],
        [-0.2624]])
tensor([[1.3416],
        [0.8512],
        [0.7306],
        [0.6197]])
  ✅ [2/3] With learned parameters (1.2ms)
tensor([[ 0.2750],
        [-0.0343]], grad_fn=<MeanBackward1>)
tensor([[0.9911],
        [0.7051]], grad_fn=<VarBackward0>)
  ✅ [3/3] Gradient flow (20.3ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (23.5ms total)
  Progress saved. Run status() to see your dashboard.

